[package]
name = "rust_mc_proto"
description = "lightweight minecraft protocol support in pure rust"

repository = "https://github.com/MeexReay/rust_mc_proto"
license-file = "LICENSE"
readme = "README.md"
keywords = ["minecraft", "protocol", "packets", "lightweight"]

version = "0.1.7"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.30", features = ["zlib"]}
bytebuffer = "2.2.0"
uuid = "1.8.0"